[package]
name = "knn_test"
version = "0.1.0"
authors = ["Florian Chlan <florian@chlan.net>"]

[dependencies]
rusty-machine = "0.5.4"
rulinalg = "0.3.7"
rustlearn = "0.4.3"
csv = "1.0"
regex = "1.0"
image = "0.19.0"
